### ISSUE TITLE
Adding a badge for a friend

### ISSUE THREAD

**Issue by KoalaBeans** [LuckFire/NameBadges#11]
Username and Discrim: Ariana aka deznuts#2929
User ID: 424555688992309248
Image Link: https://emoji.gg/assets/emoji/4073_daddy.png

**Comment by LuckFire** [comment]
i manually uploaded the image to imgur cause it has to be uploaded either on there or through discord's cdn.discordapp, mainly because vulns (incase).
but done :D

**Comment by LuckFire** [comment]
np <3
