### ISSUE TITLE
UPDATE REQUEST for azumi#6464

### ISSUE THREAD

**Issue by hayasaka-azumi** [LuckFire/NameBadges#15]
Username and Discrim: azumi#6464
User ID: 197899789252165632
Image Link: https://i.imgur.com/0hbRrJv.png

Sorry to bother you again, but it looks like my [badge got cut off.](https://i.imgur.com/4Z5oW2O.png) I chose a new one which should look okay.

**Comment by LuckFire** [comment]
updated, sorry abt that.
