### ISSUE TITLE
Badge request | PoorPockets McNewHold#1984

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [LuckFire/NameBadges#22]
Username and Discrim:PoorPockets McNewHold#1984  
User ID:277173061973835778  
Image Link:https://i.imgur.com/7ugPOvO.png

(It’s basically a still image. I don’t feel the necessity to rehost it, out of the churchofsatan website in a different format).

Due to being member of the church of Satan, I just thought it would be nice to display it next to my profile name, via the sigil of baphomet.

**Comment by LuckFire** [comment]
It has to be either on i.imgur or cdn.discordapp. If you provide me with one of those links, I can add it.

**Comment by PoorPocketsMcNewHold** [comment]
Sure thing. ![](https://i.imgur.com/FTbBslC.png)

**Comment by LuckFire** [comment]
done! :D
