### ISSUE TITLE
Badge Request for a friend

### ISSUE THREAD

**Issue by AHIRA3000** [LuckFire/NameBadges#27]
Username and Discrim: LSD_FREE_2020#3209
User ID: 631202116836261936
Image Link: https://cdn.discordapp.com/attachments/760042880491716608/772714477719126016/5607_rainbow_pride_spinning_hearts.png

**Comment by AHIRA3000** [comment]
Username and Discrim: omelet#7407
User ID: 670453754423672832
Image Link: https://i.imgur.com/4zD2ih1.png

**Comment by AHIRA3000** [comment]
two requests :) actually i might make more

**Comment by LuckFire** [comment]
the images don't seem transparent, is that intentional or?

**Comment by AHIRA3000** [comment]
> 
> 
> the images don't seem transparent, is that intentional or?

wtf

**Comment by LuckFire** [comment]
> > the images don't seem transparent, is that intentional or?
> 
> wtf

let me know when you make them transparent and i will add them

**Comment by AHIRA3000** [comment]
alright both comments are edited try now

**Comment by LuckFire** [comment]
oh.

**Comment by AHIRA3000** [comment]
> 
> 
> oh.

idk why imgur didn't make them transparent

**Comment by LuckFire** [comment]
weird. anyways added both :D

**Comment by AHIRA3000** [comment]
> 
> 
> weird. anyways added both :D

TYSM
