### ISSUE TITLE
THIS IS NOT AN ICON REQUEST

### ISSUE THREAD

**Issue by AHIRA3000** [LuckFire/NameBadges#7]
Will NameBadges be on member list soon?

**Comment by LuckFire** [comment]
not possible (atm at least, depends on if discord changes any elements)

**Comment by HooferDevelops** [comment]
maybe will make into plugin idk

**Comment by LuckFire** [comment]
do it

**Comment by HooferDevelops** [comment]
### idk

**Comment by KoalaBeans** [comment]
> maybe will make into plugin idk

let's hope it's possible 🙏

**Comment by HooferDevelops** [comment]
> > maybe will make into plugin idk
> 
> let's hope it's possible 🙏

a plugin is definitely possible i just don't know if i wanna go through all the work of a database

**Comment by LuckFire** [comment]
do it or no candy for you on halloween

**Comment by KoalaBeans** [comment]
Anything new?

**Comment by LuckFire** [comment]
nope doesnt seem like it. im gonna close this issue request but ill reopen if anything new appears (but i honestly doubt it lol)

**Comment by LuckFire** [comment]
old issue but
vizlaity and betterdiscord has support for this now, however it's most likely not coming to pc since it doesnt have the variables for it.
